### ISSUE TITLE
Feature Request: Toggle Live Auth

### ISSUE THREAD

**Issue by cdxdk** [signag/raspi-cam-srv#20]
Id like to have a toggle in the config that controls the X_feed streams authentication from and can switch between off to on so that they cannot be accessed without a user account. I've read that they previously required a login but I can't figure out a way to do this now. Can this be added?

**Comment by signag** [comment]
Hi, thanks for the request.

[V2.7.0](https://github.com/signag/raspi-cam-srv/blob/main/docs/ReleaseNotes.md#v270) now allows configuring whether or not authentication is required for streaming.

If a streaming URL is directly entered and there is no active user session, the login screen is opened.   
In this situation, the system does not remember the initially entered URL and opens the *Live* screen.   
So the streaming URL needs to be entered again. 

However, if login has already been passed and a streaming URL is entered in another tab of the browser window or another window of the **same** browser, the URL is directly opened.
