### ISSUE TITLE
Feature Request: Option to delete Photos and Videos via the Web App

### ISSUE THREAD

**Issue by CowwolfeSoftware** [signag/raspi-cam-srv#25]
I find I have to login to the Rpi OS and manually delete the photos and videos.  
Although I did see that you can hide them, I didn't see a way to remove them via the Web Interface.

**Comment by signag** [comment]
This is now available in V2.9.0.    
Also a download function has been added.

See [raspiCamSrv Photo Viewer](https://github.com/signag/raspi-cam-srv/blob/main/docs/PhotoViewer.md)

Maybe, I will add download capability also to Photo Series.
