### ISSUE TITLE
TrIgger Control Submit make server error

### ISSUE THREAD

**Issue by hinkel** [signag/raspi-cam-srv#27]
Hello  
Raspberry pi5 _8Gb
raspiCamSrv V2.9.2 seems to be an error on window Trigger __ Control__ Submit  than
 Bad Request
The browser (or proxy) sent a request that this server could not understand. 

maybe error between control and images request ?

![raspcamsrv ](https://github.com/user-attachments/assets/ba7d4b1d-356a-4745-9e38-b02a1b5469e2)

**Comment by signag** [comment]
Hi,
thanks for reporting this issue.
It is fixed in V2.10.0

**Comment by hinkel** [comment]
Hi,
tested with V2.10.1 it works again
thanks for the fast resolving 👍
